# Site settings
title: DeadPix3l | A blog about nothing. and code.
description: "A place for rambling, code, and confusion. the perfect combination"
url: "https://deadPix3l.github.io/"
author:
  name: "Skyler Curtis (@deadPix3l)"
  email: "skylerr.curtis@gmail.com"
  url: "https://deadPix3l.github.io"

# Build settings
#baseurl: /monochrome # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

host: 0.0.0.0
port: 8080
